# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kayye ##站点标题
subtitle: 我又我自由自在，长流远方
description: ##站点描述
author: Kayye ##作者
language: zh-CN  ##语言包，需要主题自带才可设置。如Jcaman自带简繁英，设置简体中文填入 zh-CN
timezone:
  
# Content
excerpt_link: Read More

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kayye.github.com.io ##站点域名
root: /
permalink: :year/:month/:day/:title/ ##文章永久链接格式，可添加.html后缀，如 :title.html
permalink_defaults:

# Directory 目录配置
source_dir: source   #源文件夹，这个文件夹用来存放内容。
public_dir: public   #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags   #标签文件夹
archive_dir: archives   #归档文件夹
category_dir: categories   #分类文件夹
code_dir: downloads/code    #nclude code 文件夹
i18n_dir: :lang   #国际化（i18n）文件夹
skip_render:   #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing 文章
new_post_name: :title.md   # 新建文章默认文件名
default_layout: post   # 默认布局
titlecase: false   # Transform title into titlecase
external_link: true   # 在新标签中打开一个外部链接，默认为true
filename_case: 0   #转换文件名，1代表小写；2代表大写；默认为0，意思就是创建文章的时候，是否自动帮你转换文件名，默认就行，意义不大。
render_drafts: false   #是否渲染_drafts目录下的文章，默认为false
post_asset_folder: true   #启动 Asset 文件夹
relative_link: false   #把链接改为与根目录的相对位址，默认false
future: true   #显示未来的文章，默认false
highlight:   #代码块的设置 
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag   分类和标签的设置
default_category: uncategorized   #默认分类
category_map:   #分类别名
tag_map:   #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination 分页
## Set per_page to 0 to disable pagination
per_page: 10   #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page   #分页目录

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: yilia ##当前主题名称

feed:
  type: atom       #feed 类型 (atom/rss2)
  path: atom.xml   #rss 路径
  limit: 20        #在 rss 中最多生成的文章数(0显示所有)

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:kayye/kayye.github.io.git,master
    gitcafe: <repository url>,[branch]

# Archives
#Archives 默认值为2,修改为1,Archives页面就只会列出标题,而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

auto_excerpt:
  enable: true
  length: 150

  # Plugins
index_generator:
  per_page: 10 ##首页默认10篇文章标题，如果值为0不分页

archive_generator:
  per_page: 10 ##归档页面默认10篇文章标题，如果值为0不分页
  yearly: true ##生成年视图
  monthly: true ##生成月视图

tag_generator:
  per_page: 10 ##标签页面默认10篇文章，如果值为0不分页

category_generator: 
  per_page: 10 ##分类页面默认10篇文章，如果值为0不分页


# ---------------------------------------------------------------

